import {
  IndianRupee,
  FileText,
  Image as ImageIcon,
  Landmark,
  Type,
  Code2,
  Briefcase,
  ArrowLeftRight,
  Wand2,
  Sparkles,
  FileJson,
  Calculator,
  Hash,
  ShieldCheck,
  Ruler,
  Scale,
  Thermometer,
  Clock,
  Smartphone,
  Box,
  Gauge,
  Download,
  Upload,
  Check,
  X,
  Search,
  Zap,
  TrendingUp,
  Star,
  Lock,
  Palette,
  Link,
  Timer,
  Calendar,
  User,
  CreditCard,
  FileSignature,
  Trash2,
  Layers,
  Split,
  RefreshCw,
  Settings,
  Package,
  KeyRound,
  QrCode,
  ScrollText,
  Percent,
  PieChart,
  ArrowUpDown,
  MoveUp,
  ListOrdered,
  Eraser,
  SpellCheck,
  CaseSensitive,
  Braces,
  Unlock,
  Fingerprint,
  Mail,
  Phone,
  Globe,
  Share2,
  House,
  type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  "indian-rupee": IndianRupee,
  "file-text": FileText,
  image: ImageIcon,
  landmark: Landmark,
  type: Type,
  "code-2": Code2,
  briefcase: Briefcase,
  "arrow-left-right": ArrowLeftRight,
  "wand-2": Wand2,
  sparkles: Sparkles,
  "file-json": FileJson,
  calculator: Calculator,
  hash: Hash,
  "shield-check": ShieldCheck,
  ruler: Ruler,
  scale: Scale,
  thermometer: Thermometer,
  clock: Clock,
  smartphone: Smartphone,
  box: Box,
  gauge: Gauge,
  download: Download,
  upload: Upload,
  check: Check,
  x: X,
  search: Search,
  zap: Zap,
  "trending-up": TrendingUp,
  star: Star,
  lock: Lock,
  palette: Palette,
  link: Link,
  timer: Timer,
  calendar: Calendar,
  user: User,
  "credit-card": CreditCard,
  "file-signature": FileSignature,
  "trash-2": Trash2,
  layers: Layers,
  split: Split,
  "refresh-cw": RefreshCw,
  settings: Settings,
  package: Package,
  "key-round": KeyRound,
  "qr-code": QrCode,
  "scroll-text": ScrollText,
  percent: Percent,
  "pie-chart": PieChart,
  "arrow-up-down": ArrowUpDown,
  "move-up": MoveUp,
  "list-ordered": ListOrdered,
  eraser: Eraser,
  "spell-check": SpellCheck,
  "case-sensitive": CaseSensitive,
  braces: Braces,
  unlock: Unlock,
  fingerprint: Fingerprint,
  mail: Mail,
  phone: Phone,
  globe: Globe,
  "share-2": Share2,
  house: House,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Hash
}